version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: jogodavelha-backend

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    container_name: jogodavelha-frontend
